substitutions:
  name: air-library
  friendly_name: "Air Quality Library"
  
esphome:
  name: $name
  friendly_name: $friendly_name

esp8266:
  board: d1_mini

# Enable logging
logger:

captive_portal:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "6989bc8ebb63dbde23e0f335d1aa9695"

wifi:
  ssid: "As you wish"
  password: "6037424348"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} Hotspot
    password: "V0cKJEQA5oAf"

time:
  - platform: homeassistant
    id: homeassistant_time
    update_interval: 60min

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO2


uart:
  rx_pin: D2
  baud_rate: 9600

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime
    update_interval: 5min

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 5min

  # air quality sensor
  - platform: pm1006
    pm_2_5:
      name: ${name} 2.5µm

switch:
  - platform: restart
    name: ${friendly_name} Restart
    

