substitutions:
  node_name: lolin-s3-mini-pro-radar
  node_friendly_name: Vehicle Speed Radar

# Board: WEMOS LOLIN S3 Mini Pro
# Definition: definitions/boards/lolin_s3_mini_pro/manifest.yaml

esphome:
  name: ${node_name}
  friendly_name: ${node_friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    
logger:

api:
  encryption:
    key: "yB6qAT3jQGKg6BN1K2RnnB/Q62/65ed+M5aXm6I9NLw="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: lolin-s3-mini-p Fallback Hotspot
    password: "sfzD4RJfxfwh"

captive_portal:
