esphome:
  name: lolinc3minitest1
  friendly_name: LolinC3miniTest1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "OeCMBQIq8UWFqYu0scRSvvFKGff1On2YfsArfmYef2o="

ota:
  - platform: esphome
    password: "a66dbb4d7d41e1e0a480ac1725dbada8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lolinc3Minitest1"
    password: "2DmF0a93n8wR"

captive_portal:
    